### ISSUE TITLE
strokeColor by data value is not working

### ISSUE THREAD

**Issue by ramiroaznar** [GoogleCloudPlatform/bigquery-geo-viz#11]
I am trying to style my LineStrings by a categorical value from one of my columns. But it looks like the feature is broken, the geometries are only being styled using the first color value.

### STR

1. Query a LineString dataset
2. Go to STYLE and enable the `data-driven` option from the strokeColor section
3. Select a categorical column 
4. Fill it with the proper unique values
5. Select any color combination

### Expected result

LineStrings should be styled by categorical values.

### Current Result

![bug](https://user-images.githubusercontent.com/5215798/66392709-ef5f9980-e9d0-11e9-99fd-17b2905663d3.png)

Some errors are shown in the console. LineStrings are only plotted using the first color value.

### OS and device

Chrome 77
Ubuntu 18

**Comment by donmccurdy** [comment]
I'm not able to reproduce this –  can you share some example data or a query? There may be something about the particular data you're reading that causes the error, but a simple LineString dataset is working fine for me. For example:

```sql
SELECT
  ST_GeogFromText("LINESTRING (30 10, 10 30, 40 40)") geo,
  "unsafe" condition;
```

![Screen Shot 2019-10-10 at 10 34 50 AM](https://user-images.githubusercontent.com/1848368/66592291-9e26e580-eb49-11e9-8e59-a560b443a8a7.png)
![Screen Shot 2019-10-10 at 10 35 11 AM](https://user-images.githubusercontent.com/1848368/66592316-a54df380-eb49-11e9-8acb-33a63b2f7a3a.png)

**Comment by ramiroaznar** [comment]
You are right. I have also getting the same result when styling the centroids of my linestrings. I am going to try to clean my data, but it would be great if there were any useful error pointing to the problem. As soon as I find the conflict row value, I will share it here.

**Comment by donmccurdy** [comment]
Ok – happy to fix this if you can share a query that reproduces the error.

**Comment by ramiroaznar** [comment]
Hi Don,

Sorry for the lack of response. You can keep it close. I cannot share the
data, but it was definitively something related to the values. I do not
recall it was null or invalid geometries though. Thanks anyway!
