### ISSUE TITLE
circleRadius data-driven not working

### ISSUE THREAD

**Issue by brodiemackenzie** [GoogleCloudPlatform/bigquery-geo-viz#12]
Following this tutorial in the BigQuery GIS documentation;
https://cloud.google.com/bigquery/docs/gis-tutorial-hurricane

In the "To format your map" section, step 9, the circleRadius data-driven formatting is not styling the points. Expect point radius to change based on the data as per the tutorial.

**Comment by donmccurdy** [comment]
The units of measurement have changed since that tutorial was written – they used to be in pixels, but are now in meters. So in this particular case, you'll need much larger `circleRadius` values.

**Comment by donmccurdy** [comment]
I've reported the issue on the tutorial. Thanks for letting us know!
