### ISSUE TITLE
Styles are not working (e.g. circleRadius)

### ISSUE THREAD

**Issue by dagamargit** [GoogleCloudPlatform/bigquery-geo-viz#24]
Hi,

I have been using bigquery-geo-viz for a while in several courses. Today, I was noticed that several features related to styles are not working as usual.

To be sure, I have followed the "hurricane track example" from https://cloud.google.com/bigquery/docs/gis-tutorial-hurricane?hl=es-419

Usually, when I reached step 2 in the bigquey-geo-viz (select geometry column field), the google map points were shown. Now, they remain the same.

Moreover, when I try to define styles (e.g. circleRadius) following the tutorial, nothing changes. Only some small red points are shown

![circleradius not working](https://user-images.githubusercontent.com/34348502/69484823-ff73f100-0e37-11ea-90d4-f2eace8b50f8.png)

Kind regards,
Daniel.

**Comment by donmccurdy** [comment]
What has changed since earlier this year is that the circle radius is now measured in meters, not pixels — so 135m at this scale will be a single pixel. Larger values should appear as you're expecting, though.

**Comment by dagamargit** [comment]
Hi,
Yes, you're right! It was only a not updated instructable!
Moreover, the bigquerygeoviz GUI says: "radius of the circle representing a point in meter".

Thanks a lot.
