### ISSUE TITLE
Points are off the map

### ISSUE THREAD

**Issue by sciciliani** [GoogleCloudPlatform/bigquery-geo-viz#33]
Running this example query and visualizing through bigquerygeoviz

SELECT ST_GEOGPOINT(lat, lon) as geo FROM `properati-data-public`.`properties_ar`.`properties_sell_201802`
WHERE lat_lon <> ''
limit 500

As you see results are outside the continent

![Screen Shot 2020-02-05 at 12 19 42](https://user-images.githubusercontent.com/1580244/73855022-3429fe80-4812-11ea-963f-94857c3d80a7.png)

Same point from resultset in Google Maps provides correct location

![Screen Shot 2020-02-05 at 12 23 45](https://user-images.githubusercontent.com/1580244/73855240-8834e300-4812-11ea-8d6a-621ad61de7ea.png)

**Comment by donmccurdy** [comment]
The `ST_GEOGPOINT` SQL function requires `lng, lat` rather than `lat, lng` — see https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions#st_geogpoint.
