### ISSUE TITLE
Cannot type into query box or see anything

### ISSUE THREAD

**Issue by fresh-info-kallen** [GoogleCloudPlatform/bigquery-geo-viz#51]
![image](https://user-images.githubusercontent.com/74892357/172994441-febbe8eb-8b85-48ae-b538-7c338de88d28.png)

Hi

I am not able to type anything into the query box here. It also looks like its glitched out;

**Comment by mentin** [comment]
Issue confirmed.
Created https://github.com/GoogleCloudPlatform/bigquery-geo-viz/pull/52,
we'll try to publish new version next week.

**Comment by mentin** [comment]
Updated GeoViz, please verify.
(I had to load use URI "https://bigquerygeoviz.appspot.com/?" to update local cache, but probably should work now without ? too).

**Comment by gmerrall** [comment]
Can confirm it's working fine again

**Comment by imiller1985** [comment]
I am seeing this issue again. Started in the past couple of weeks.
