### ISSUE TITLE
Authorize does not work

### ISSUE THREAD

**Issue by tychovdo** [GoogleCloudPlatform/bigquery-geo-viz#8]
After pressing the "Authorize" button the google login pop-up does show, but afterwards nothing happens. "Authorize" button remains active and "Data" and "Style" label stay greyed-out. I did receive an email confirming the authorization. II tried it on two different systems.

Is the authorization (temporary?) broken or should I do something different?

Very much looking forward to a reply. Thanks in advance.

**Comment by donmccurdy** [comment]
I'm not sure why this would happen... Could you try logging in, using the same account, from an "incognito window" in chrome or a "private window" in Firefox?

**Comment by jpbrody** [comment]
I had this problem also. 

I solved it by allowing third party cookies.

**Comment by jpbrody** [comment]
> After pressing the "Authorize" button the google login pop-up does show, but afterwards nothing happens. "Authorize" button remains active and "Data" and "Style" label stay greyed-out. I did receive an email confirming the authorization. II tried it on two different systems.
> 
> Is the authorization (temporary?) broken or should I do something different?
> 
> Very much looking forward to a reply. Thanks in advance.

I had this problem too.
I solved it by allowing third party cookies.

**Comment by hormati** [comment]
Hi Jim,
Sorry for the delayed response. I was out of office. Are you still
experiencing an issue here?

Amir

**Comment by 4bh1shek** [comment]
I am still facing the same issue what to do?
